name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Har 4 soatda avtomatik qayta ishga tushib turadi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Org if missing
      run: python add_org.py || true

    - name: Run bot
      run: python hr.py
